language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base qt58serialport
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - mkdir -p appdir/usr/bin ; mkdir -p appdir/usr/share/{applications,icons} ; cd appdir
  - cp ../esptool-gui usr/bin
  - mkdir -p usr/bin/tool-esptool 
  - cp ../tools-linux/tool-esptool/esptool usr/bin/tool-esptool/
  - cp ../*.desktop .
  - touch esptool-gui.png # FIXME
  - cd .. 
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/esptool-gui -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/bin/esptool-gui -appimage 
  - curl --upload-file ./esptool-gui-*.AppImage https://transfer.sh/esptool-gui-git.$(git rev-parse --short HEAD)-x86_64.AppImage 
